export const ingredients = [ 
    '151 proof rum',
    '7-up',
    'Absinthe',
    'Absolut citron',
    'Absolut Kurant',
    'Absolut Peppar',
    'Absolut Vodka',
    'Advocaat',
    'Agave syrup',
    'Ale',
    'Allspice',
    'Almond',
    'Amaretto',
    'Angelica Root',
    'Angostura Bitters',
    'Anis',
    'Anise',
    'Anisette',
    'Aperol',
    'Apfelkorn',
    'Apple Brandy',
    'Apple Cider',
    'Apple Juice',
    'Apple schnapps',
    'Applejack',
    'Apricot Brandy',
    'Apple',
    'Apricot',
    'Aquavit',
    'Bacardi Limon',
    'Bacardi',
    'Baileys irish cream',
    'Banana liqueur',
    'Banana',
    'Beer',
    'Benedictine',
    'Berries',
    'Bitter lemon',
    'Bitters',
    'Black Sambuca',
    'Blackberry Brandy',
    'Blackcurrant cordial',
    'Blackcurrant squash',
    'Blended Whiskey',
    'Blue Curacao',
    'Blueberry schnapps',
    'Bourbon',
    'Brown Sugar',
    'Butter',
    'Butterscotch schnapps',
    'Cachaca',
    'Calvados',
    'Campari',
    'Canadian whisky',
    'Cantaloupe',
    'Carbonated soft drink',
    'Carbonated water',
    'Cardamom',
    'Carrot',
    'Celery salt',
    'Celery',
    'Chambord raspberry liqueur',
    'Champagne',
    'Cherry Brandy',
    'Cherry Heering',
    'Cherry juice',
    'Cherry liqueur',
    'Chocolate ice-cream',
    'Chocolate liqueur',
    'Chocolate syrup',
    'Chocolate',
    'Cider',
    'Cinnamon',
    'Citrus vodka',
    'Cloves',
    'Club Soda',
    'Coca-Cola',
    'Cocoa Powder',
    'Coconut liqueur',
    'Coconut Milk',
    'Coconut rum',
    'Coffee brandy',
    'Coffee liqueur',
    'Coffee',
    'Cognac',
    'Cointreau',
    'Condensed milk',
    'Coriander',
    'Corn syrup',
    'Cornstarch',
    'Corona',
    'Cranberries',
    'Cranberry Juice',
    'Cranberry vodka',
    'Cream of Coconut',
    'Cream',
    'Creme de Almond',
    'Creme De Banane',
    'Creme de Cacao',
    'Creme de Cassis',
    'Creme de Noyaux',
    'Crown Royal',
    'Cumin seed',
    'Curacao',
    'Cynar',
    'Daiquiri mix',
    'Dark Creme de Cacao',
    'Dark Rum',
    'demerara sugar',
    'Drambuie',
    'Dry Vermouth',
    'Dubonnet blanc',
    'Dubonnet Rouge',
    'Egg White',
    'Egg Yolk',
    'Egg',
    'Erin Cream',
    'Espresso',
    'Everclear',
    'Firewater',
    'Forbidden Fruit',
    'Frangelico',
    'Fruit juice',
    'Fruit punch',
    'Fruit',
    'Galliano',
    'Gin',
    'Ginger Ale',
    'Ginger beer',
    'Ginger',
    'Godiva liqueur',
    'Gold rum',
    'Gold Tequila',
    'Goldschlager',
    'Grain Alcohol',
    'Grand Marnier',
    'Grape juice',
    'Grape soda',
    'Grapefruit Juice',
    'Grapes',
    'Green Chartreuse',
    'Green Creme de Menthe',
    'Green Ginger Wine',
    'Grenadine',
    'Ground Almonds',
    'Guava juice',
    'Guinness stout',
    'Half-and-half',
    'Hazelnut liqueur',
    'Heavy cream',
    'Honey',
    'Hot Chocolate',
    'Hot Damn',
    'Hpnotiq',
    'Ice',
    'Iced tea',
    'Irish cream',
    'Irish Whiskey',
    'Jack Daniels',
    'Jello',
    'Jagermeister',
    'Jim Beam',
    'Johnnie Walker',
    'Kahlua',
    'Key Largo Schnapps',
    'Kirschwasser',
    'Kiwi liqueur',
    'Kiwi',
    'Kool-Aid',
    'Kummel',
    'Lager',
    'Lemon Juice',
    'Lemon Peel',
    'Lemon vodka',
    'Lemon-lime soda',
    'lemon-lime',
    'lemon',
    'Lemonade',
    'Light Cream',
    'Light Rum',
    'Lillet',
    'Lime juice cordial',
    'Lime Juice',
    'Lime liqueur',
    'Lime vodka',
    'Lime',
    'Limeade',
    'Madeira',
    'Malibu Rum',
    'Mango',
    'Maple syrup',
    'Maraschino Cherry',
    'Maraschino Liqueur',
    'Maui',
    'Mezcal',
    'Midori melon liqueur',
    'Milk',
    'Mint syrup',
    'Mint',
    'Mountain Dew',
    'Olive',
    'Orange Bitters',
    'Orange Curacao',
    'Orange Juice',
    'Orange liqueur',
    'Orange Peel',
    'Orange rum',
    'Orange',
    'Oreo cookie',
    'Orgeat Syrup',
    'Ouzo',
    'Papaya',
    'Passion fruit juice',
    'Passion fruit syrup',
    'Passoa',
    'Peach brandy',
    'Peach Nectar',
    'Peach Schnapps',
    'Peach Vodka',
    'Peachtree schnapps',
    'Peppermint Schnapps',
    'Pepsi Cola',
    'Peychaud bitters',
    'Pina colada mix',
    'Pineapple Juice',
    'Pineapple rum',
    'Pineapple vodka',
    'Pineapple',
    'Pink lemonade',
    'Pisang Ambon',
    'Pisco',
    'Port',
    'Powdered Sugar',
    'Raspberry liqueur',
    'Raspberry Vodka',
    'Red Wine',
    'Ricard',
    'Root beer',
    'Roses sweetened lime juice',
    'Rum',
    'Rumple Minze',
    'Rye whiskey',
    'Sake',
    'Salt',
    'Sambuca',
    'Sarsaparilla',
    'Schweppes Lemon',
    'Schweppes Russchian',
    'Scotch',
    'Sherbet',
    'Sherry',
    'Sloe Gin',
    'Soda Water',
    'Sour Mix',
    'Southern Comfort',
    'Spiced Rum',
    'Sprite',
    'Strawberries',
    'Strawberry liqueur',
    'Strawberry Schnapps',
    'Sugar Syrup',
    'Sugar',
    'Surge',
    'Sweet and Sour',
    'Sweet Vermouth',
    'Tabasco Sauce',
    'Tea',
    'Tennessee whiskey',
    'Tequila rose',
    'Tequila',
    'Tia Maria',
    'Tomato Juice',
    'Tonic Water',
    'Triple Sec',
    'Tropicana',
    'Tuaca',
    'Vanilla extract',
    'Vanilla Ice-Cream',
    'Vanilla liqueur',
    'Vanilla schnapps',
    'Vanilla syrup',
    'Vanilla vodka',
    'Vermouth',
    'Vodka',
    'Water',
    'Whipped Cream',
    'Whiskey',
    'Whisky',
    'White Creme de Menthe',
    'White Rum',
    'White Wine',
    'Wild Turkey',
    'Wine',
    'Yellow Chartreuse',
    'Yoghurt',
    'Yukon Jack',
    'Zima',
]